# Generated by Django 3.2.12 on 2023-04-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='blogs/default.png', upload_to='profiles'),
        ),
    ]
